parameters:
  Artifacts: []
  TestPipeline: false
  ArtifactName: 'not-specified'
  # Publish to https://dev.azure.com/azure-sdk/public/_packaging?_a=feed&feed=azure-sdk-for-net
  DevOpsFeedId: '29ec6040-b234-4e31-b139-33dc4287b756/fa8c16a3-dbe0-4de2-a297-03065ec1ba3f'
  TargetDocRepoOwner: 'not-specified'
  TargetDocRepoName: 'not-specified'


stages:
  - ${{if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'internal'))}}:
    - ${{ each artifact in parameters.Artifacts }}:
      - ${{if ne(artifact.skipReleaseStage, 'true')}}:
        - stage:
          variables:
            - template: /eng/pipelines/templates/variables/globals.yml
            - template: /eng/pipelines/templates/variables/image.yml
          displayName: 'Release: ${{artifact.name}}'
          condition: and(succeeded(), ne(variables['SetDevVersion'], 'true'), ne(variables['Skip.Release'], 'true'), ne(variables['Build.Repository.Name'], 'Azure/azure-sdk-for-net-pr'))
          jobs:
            - ${{if ne(artifact.skipPublishPackage, 'true')}}:
              - ${{if ne(artifact.skipSymbolsUpload, 'true')}}:
                - deployment: UploadSymbols
                  displayName: Upload Symbols to Symbols Server
                  condition: and(succeeded(), ne(variables['Skip.SymbolsUpload'], 'true'))
                  environment: package-publish
                  variables:
                    SdkRepoPath: $(Pipeline.Workspace)/azure-sdk-for-net
                    BuildToolsRepoPath: $(Pipeline.Workspace)/azure-sdk-build-tools
                  pool:
                    name: azsdk-pool-mms-win-2022-general
                    image: azsdk-pool-mms-win-2022-1espt
                    os: windows

                  strategy:
                    runOnce:
                      deploy:
                        steps:
                          - template: /eng/common/pipelines/templates/steps/sparse-checkout.yml
                            parameters:
                              SkipCheckoutNone: true
                              Repositories:
                                - Name: $(Build.Repository.Name)
                                  Commitish: $(Build.SourceVersion)
                                  WorkingDirectory: $(SdkRepoPath)
                              Paths:
                                - "/eng/scripts"
                          - checkout: azure-sdk-build-tools
                            path: azure-sdk-build-tools
                          - pwsh: |
                              Write-Host "System.DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)"
                              Write-Host "Pipeline.Workspace: $(Pipeline.Workspace)"

                              pushd $(Pipeline.Workspace)
                              ls
                            displayName: 'Debug Paths'
                          - task: PowerShell@2
                            displayName: 'Convert symbols to Windows PDB format'
                            inputs:
                              pwsh: true
                              filePath: $(SdkRepoPath)/eng/scripts/symbols/Convert-SymbolsToWindowsPdb.ps1
                              arguments: >
                                -PdbToolPath $(BuildToolsRepoPath)/tools/symboltool/pdb2pdb.exe
                                -PackagesPath $(Pipeline.Workspace)/${{parameters.ArtifactName}}/${{artifact.name}}
                                -OutputPath $(Build.ArtifactStagingDirectory)/symbols
                          - task: AzurePowershell@5
                            displayName: 'Reserve symbols api request name'
                            inputs:
                              pwsh: true
                              azureSubscription: 'Azure SDK Symbols Publishing'
                              azurePowerShellVersion: 'LatestVersion'
                              ScriptType: 'FilePath'
                              ScriptPath: $(SdkRepoPath)/eng/scripts/symbols/New-SymbolsApiRequestName.ps1
                              ScriptArguments: >
                                -ProjectName 'azure-sdk'
                                -VariableName 'SymbolsRequestName'
                          - task: PublishSymbols@2
                            displayName: 'Publish symbols to Azure DevOps'
                            inputs:
                              SymbolsFolder: '$(Build.ArtifactStagingDirectory)/symbols'
                              SearchPattern: '**/*.pdb'
                              SymbolServerType: 'TeamServices'
                              SymbolsArtifactName: '$(SymbolsRequestName)'
                          - task: AzurePowershell@5
                            displayName: 'Request SymWeb and MSDL api publishing'
                            inputs:
                              pwsh: true
                              azureSubscription: 'Azure SDK Symbols Publishing'
                              azurePowerShellVersion: 'LatestVersion'
                              ScriptType: 'FilePath'
                              ScriptPath: $(SdkRepoPath)/eng/scripts/symbols/Invoke-SymbolsApiRequest.ps1
                              ScriptArguments: >
                                -ProjectName 'azure-sdk'
                                -RequestName '$(SymbolsRequestName)'
                                -Wait
